name: CI
on:
  push:
    branches:
      - main

jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Validate Blueprints
      id: validate
      uses: QualiTorque/torque-validate-bp-action@bug/list-blueprints
      with:
        space: dev
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_url: https://preview.qtorque.io

