name: CI
on:
  push:
    branches:
      - main

jobs:
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Validate Blueprints
      id: validate
      uses: QualiTorque/torque-validate-blueprints@v1
      with:
        space: dev
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        torque_hostname: preview.qtorque.io

